apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credentials
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: services/renovate/credentials
